### ISSUE TITLE
An exception was raised while creating "ScnSocialAuth-User"; no instance returned

### ISSUE THREAD

**Issue by padalec** [SocalNick/ScnSocialAuth#222]
I create a fresh zend sceleton application and try integrate with SocalNick but after go to /user/login 
I have this error:
```**An exception was raised while creating "ScnSocialAuth-User"; no instance returned**
#0 /home/vagrant/autentika/zftest/vendor/zendframework/zend-servicemanager/src/AbstractPluginManager.php(284): Zend\ServiceManager\ServiceManager->createServiceViaCallback(Array, 'scnsocialauthus...', 'ScnSocialAuth-U...')
#1 /home/vagrant/autentika/zftest/vendor/zendframework/zend-servicemanager/src/AbstractPluginManager.php(242): Zend\ServiceManager\AbstractPluginManager->createServiceViaCallback(Array, 'scnsocialauthus...', 'ScnSocialAuth-U...')
#2 /home/vagrant/autentika/zftest/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(638): Zend\ServiceManager\AbstractPluginManager->createFromFactory('scnsocialauthus...', 'ScnSocialAuth-U...')
#3 /home/vagrant/autentika/zftest/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(598): Zend\ServiceManager\ServiceManager->doCreate('ScnSocialAuth-U...', 'scnsocialauthus...')
#4 /home/vagrant/autentika/zftest/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(530): Zend\ServiceManager\ServiceManager->create(Array)
#5 /home/vagrant/autentika/zftest/vendor/zendframework/zend-servicemanager/src/AbstractPluginManager.php(116): Zend\ServiceManager\ServiceManager->get('ScnSocialAuth-U...', false)
#6 /home/vagrant/autentika/zftest/vendor/zendframework/zend-mvc/src/Controller/ControllerManager.php(137): Zend\ServiceManager\AbstractPluginManager->get('ScnSocialAuth-U...', Array, false)
#7 /home/vagrant/autentika/zftest/vendor/zendframework/zend-mvc/src/DispatchListener.php(76): Zend\Mvc\Controller\ControllerManager->get('ScnSocialAuth-U...')
#8 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#9 /home/vagrant/autentika/zftest/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#10 /home/vagrant/autentika/zftest/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#11 /home/vagrant/autentika/zftest/vendor/zendframework/zend-mvc/src/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#12 /home/vagrant/autentika/zftest/public/index.php(17): Zend\Mvc\Application->run()
#13 {main}```

**Comment by padalec** [comment]
Configuration was copied from your sandbox application

**Comment by padalec** [comment]
OK I fix this the problem was in db configuration key.
